// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Transaction struct {
	ID            string  `json:"id"`
	TransactionID string  `json:"transactionId"`
	MedicineName  string  `json:"medicineName"`
	Quantity      int32   `json:"quantity"`
	Price         float64 `json:"price"`
	CreatedAt     string  `json:"createdAt"`
}

type TransactionInput struct {
	TransactionID string  `json:"transactionId"`
	MedicineName  string  `json:"medicineName"`
	Quantity      int32   `json:"quantity"`
	Price         float64 `json:"price"`
}
